name : Test Secrets
on: push
jobs:
  display_values:
    runs-on: ubuntu-lastest
    steps:
      - run: |
          echo "${{ secrets.DATABASE_PASSWORD }}"
          echo "${{ vars.VERSION }}"
      
