name : Test Cache
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir dependencies
          echo "Mon application" > ./dependencies/my_app.txt
      - name: Cache
        uses: actions/cache@v3.3.2
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: dependencies/
          # An explicit key for restoring and saving the cache
          key: mon_cache
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - run: |
          ls
          cat my_app.txt
          
      
